### ISSUE TITLE
Question about scope

### ISSUE THREAD

**Issue by flyaruu** [strimzi/strimzi-mqtt-bridge#35]
Hey all,

I'm wondering if the scope is only to map mqtt->kafka or also from kafka->mqtt? I don't see any mention of kafka->mqtt, but in any case I think it would be good to mention that explicitly.

**Comment by ppatierno** [comment]
As part of the LFX mentoring program, the bridge is focused on MQTT -> Kafka to cover most of the IoT related use cases with devices sending telemetry data and backend application processing them.
Right now there is no actual plan to make the Kafka -> MQTT communication in place. MQTT subscriptions are usually used for getting "command"(s) from a backend system (It's rarely used by MQTT devices to just get information). Because of the "command" pattern, I don't see Kafka to be the best fit because it would require a request/reply pattern (command sent/command outcome).
Anyway, you are right it would be better to mention that in the landing page.

**Comment by flyaruu** [comment]
Makes sense. Thanks!
